program io_write_file
    implicit none
    integer :: unit_num, i

    open(newunit=unit_num, file="output.txt", status="replace", action="write")

    write(unit_num, '(A)') "Report generated by Fortran"
    write(unit_num, '(A)') "----------------------------"

    do i = 1, 3
        write(unit_num, '(A, I0, A, I0)') "Line ", i, ": value = ", i * i
    end do

    close(unit_num)

    print *, "File written successfully."
end program io_write_file
